# Generated by Django 4.0.5 on 2022-06-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('album_art', models.ImageField(upload_to='images/album_art/')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
            ],
        ),
    ]
