# Generated by Django 4.0.5 on 2022-07-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0004_album_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='djamming.track'),
        ),
    ]
