# Generated by Django 4.0.5 on 2022-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0011_remove_album_tracks_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='song',
            field=models.FileField(upload_to='static/media/tracks/'),
        ),
    ]
