# Generated by Django 4.0.5 on 2022-07-06 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0012_track_name_alter_track_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='djamming.album'),
        ),
    ]
