# Generated by Django 4.0.5 on 2022-07-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0013_alter_artist_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
    ]
