# Generated by Django 4.0.5 on 2022-07-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0014_rename_artist_name_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='djamming.artist'),
        ),
    ]
