# Generated by Django 4.0.5 on 2022-07-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0016_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='album',
        ),
    ]
