# Generated by Django 4.0.5 on 2022-07-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0019_alter_album_artist_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='djamming.artist'),
        ),
    ]
