# Generated by Django 4.0.5 on 2022-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djamming', '0026_artist_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.ImageField(null=True, upload_to='static/images/album_art/'),
        ),
    ]
